### ISSUE TITLE
how to enable nbextensions in conda env

### ISSUE THREAD

**Issue by marscher** [markovmodel/pyemma_tutorials#10]
It seems that a local notebook.json file is ignored, so we need another solution for this.

**Comment by marscher** [comment]
one can specify the config, when starting the notebook server: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/config.html#jupyter-configuration-filenames

**Comment by cwehmeyer** [comment]
What about this?

```Jupyter Notebook
%%javascript
Jupyter.utils.load_extensions('exercise2/main')
```

According to https://mindtrove.info/4-ways-to-extend-jupyter-notebook/#nb-extensions, this snippet will load an installed `exercise2` extension; and we have it installed via `environment.yml`.
