### ISSUE TITLE
mybinder

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#101]
We should explore the https://mybinder.org option to run the notebooks without installation.

**Comment by marscher** [comment]
On 11.07.2018 10:05, Christoph Wehmeyer wrote:
> We should explore the https://mybinder.org option to run the notebooks without installation.
> 
> 
I have looked into this, we need to define our own docker container,
because we are using a more advanced setup. I can do this.

**Comment by marscher** [comment]
from the binder documentation:

Note

Binder is a research pilot, whose main goal is to understand usage patterns and workloads for future evolution and development. It is not a service that can be relied on for critical operations.

**Comment by marscher** [comment]
https://mybinder.org/v2/gh/marscher/pyemma_tutorials/binder

please feel free to test.
