### ISSUE TITLE
Citations in notebooks

### ISSUE THREAD

**Issue by marscher** [markovmodel/pyemma_tutorials#105]
As it has been requested during the seminar, we should include citations in the notebooks. There is a nice (and working) extension, which has support for bibtex.

It works by having a secret cell (by notebook) or a bibliography.ipynb (shared) containing the references. Inserting citations is super easy and the references will be updated by clicking one button. 

https://github.com/Calysto/notebook-extensions/blob/master/Screenshot%20from%202017-08-09%2019-48-12.png

If we want to use it, I can make this extension available on conda-forge.

ATM: it can be installed via conda install calysto-nb-extensions blas -c defusco

**Comment by cwehmeyer** [comment]
Let's test it first.

We have a bibtex file (in the manuscript repository) where I would like to collect all citations. Can we import this file somehow into the notebooks?

**Comment by marscher** [comment]
On 12.07.2018 10:53, Christoph Wehmeyer wrote:
> Let's test it first.
> 
> We have a bibtex file (in the manuscript repository) where I would like to collect all citations. Can we import this file somehow into the notebooks?
> 

I guess we can import it with a manual step (citations do not change all
the time, so this should be fine) - or provide a script which generates
the Bibliography.ipynb

The only difference to the input bib file is the wrapping with the
 tags

**Comment by marscher** [comment]
Since the output of this extension is static text, we do not need the user to install anything!
