### ISSUE TITLE
nglview problems

### ISSUE THREAD

**Issue by psolsson** [markovmodel/pyemma_tutorials#12]
nglview widget fails silently -- no output in jupyter notebook or console. I have tried a perform a fresh install according to [this guide](https://github.com/SBRG/ssbio/wiki/Troubleshooting#fresh-install) and tried both Firefox and Safari browsers. I have tried versions nglview 1.1.2 and 1.1.3.

**Note**  I have previously used nglview with molPX.

**Some details:**
Checking if nglview is registered as an extension
```
bristolscale:notebooks solsson$ jupyter-nbextension list 
Known nbextensions:
  config dir: /Users/solsson/.jupyter/nbconfig
    notebook section
      nglview/extension  enabled 
      - Validating: OK
      nglview-js-widgets/extension  enabled 
      - Validating: OK
      widgets/notebook/js/extension  enabled 
      - Validating: problems found:
        - require?  X widgets/notebook/js/extension
  config dir: /Users/solsson/miniconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nglview-js-widgets/extension disabled
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled 
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```
Different version info:
```
bristolscale:notebooks solsson$ conda list | grep widgetsnbextension
widgetsnbextension        3.2.1                    py36_0    conda-forge
bristolscale:notebooks solsson$ conda list | grep ipywidgets
ipywidgets                7.2.1                    py36_1    conda-forge
bristolscale:notebooks solsson$ conda list | grep ipython
ipython                   6.2.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
bristolscale:notebooks solsson$ conda list | grep nglview
nglview                   1.1.2                    py36_1    bioconda
```
Note I have also tried nglview 1.1.3 from conda-forge.

**Comment by marscher** [comment]
Did you create a new environment? Has conda-forge the highest priority in this environment?
It seems like the core nbwidgets are not functioning properly:
```
      widgets/notebook/js/extension  enabled 
      - Validating: problems found:
        - require?  X widgets/notebook/js/extension
```
I should write an install guide for this repo.

**Comment by marscher** [comment]
mixing bioconda with conda-forge may also cause problems, because the bioconda installation does not uninstall the javascripts properly.

Can you please create a fresh environment like this, and report if it works then:

```
curl  https://raw.githubusercontent.com/markovmodel/PyEMMA_tutorials/master/environment.yml > env.yml
conda env create -f env.yml
```

**Comment by marscher** [comment]
On 28.05.2018 18:23, Simon Olsson wrote:
> Just tried this. Same issue.
> 
Well, it works for other people. So I assume you have not deleted all of
the leftovers from different installation methods.

**Comment by cwehmeyer** [comment]
We might need to add a short explanation how to fix this. Maybe in the README?

**Comment by marscher** [comment]
done in d736d1587ea51d42d4e62669e4c2e9074116998d
