### ISSUE TITLE
Accompanying image

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#129]
From the author instructions:

> An image to accompany the paper at least 300 x 200 pixels, any standard image format, color preferred, less than 1MB in size). This image is important to choose carefully, as it is the image that will appear on the article’s front page and whenever the paper is shared on social media. We suggest something evocative of the research, but containing less scientific detail than, say, the table of contents image for an ACS journal.

**Comment by thempel** [comment]
Done. Can be found in manuscript/figures/tutorials-logo.png
