### ISSUE TITLE
How to compute experimental observables is not mentioned.

### ISSUE THREAD

**Issue by psolsson** [markovmodel/pyemma_tutorials#13]
This could fit into notebook 4, or even have its own dedicated notebook. With its own notebook we could use the PyEMMA [AMM tutorial](http://www.emma-project.org/latest/generated/augmented_markov_model_walkthrough.html#) and my [relaxation dispersion](https://github.com/psolsson/NMR_ChemEx_Pred) tutorial as a scaffold as it illustrates all these points: computation of observables (stationary and dynamic) and use of experimental restraints in MSM estimation. I can prepare a reduced version with some exercises of this notebook if it fits within the scope?

**Comment by cwehmeyer** [comment]
I am in favour of a new notebook on this particular topic. We could use one or two constructed example(s) based on the three known systems first and then make exercises using @psolsson's data.
