### ISSUE TITLE
question regarding dtrajs_concatenated

### ISSUE THREAD

**Issue by gokulalgates** [markovmodel/pyemma_tutorials#135]
While working on its calculation.. we are using cluster.dtrajs. why are we not using dtrajs concatenated as they represent the complete list of trajectories using following code? 

its = pyemma.msm.its(dtrajs_concatenated, lags=20000, nits=4)#, errors='bayes')
pyemma.plots.plot_implied_timescales(its, units='ns', dt=0.02);

**Comment by thempel** [comment]
As soon as you start counting transitions, concatenating trajectories introduces artifacts. It only makes sense for e.g. histograms, where you do not take any transitions into account.

Imagine you have two discrete trajectories [1,2,1,2,1,2,1] and [0, 0, 0, 0, 0]. If you concatenate those, you will introduce a transition from / to state 0 from the other states (depending on the order of concatenation). But this transition was never observed in your data. If you build a Markov model from that, it will naturally come out wrong and estimate transition probabilities between states that are not connected and give you artificial implied timescales.

Does that answer your question?

**Comment by cwehmeyer** [comment]
We need to clarify this in the notebook.

**Comment by gokulalgates** [comment]
Thank you! I understood I have another question. 
I know its silly to ask this question, Do we need to Fit trajectory even if we select backbone angle?

**Comment by thempel** [comment]
Sorry, I don't understand. What do you exactly mean by fit trajectory? (Maybe post the code that you think might not be needed?)

**Comment by gokulalgates** [comment]
Sorry, For not being clear, I mean to ask you do we need to RMSD-align the structure of trajectory for backbone angle as a feature? I hope we don't have to align as the distance is rotationally invariant while calculating covariance. Am I right about it?
