### ISSUE TITLE
Add basic MSM theory

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#136]
Rewrite Section 2.1 to include the basic MSM theory after the literature overview.

This needs to include (among other points):

- [x] lag times (#144)
- [x] transition matrix definition and properties
- [x] VAMP-2 score (#142, #144, #148)
- [x] TICA (#139, #146)
- [x] left/right eigenvectors (#145)
- [x] CK test (#140)

**Comment by brookehus** [comment]
Will aim to draft this tomorrow afternoon, US eastern time

**Comment by brookehus** [comment]
Most done in #150 ; more of the CK stuff is in the current PRs I think (e.g. #155).

**Comment by cwehmeyer** [comment]
@franknoe proposed additional changes to the theory section:

- [ ] moving the literature overview into scope
- [ ] focus on equilibrium simulations
- [ ] removing left eigenvector text/equations beyond stationary distribution
- [ ] remove broken line from Fig.2b and plot from y>2.5
- [ ] replace sample density by sample free energy in Fig.2c (the reweighted plot is in Fig.4a)
- [ ] use thinner lines in Fig.2d
- [ ] add text on TICA
- [ ] add text on HMMs

**Comment by cwehmeyer** [comment]
closed via #169
