### ISSUE TITLE
Fetching data for offline use

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#14]
The new README shows a method to fetch all data prior to running the first notebook. The last line,

```bash
mdshare fetch *
```

however, cannot (yet) work. We could implement
1. an mdshare-included command line tool to fetch the entire collection or
2. include a script in the tutorial repo to handle the fetching.

Any preferences, @marscher?

**Comment by marscher** [comment]
A command line tool would increase usability, however it does not seem to be necessary. Replaced the line with a python command.

**Comment by cwehmeyer** [comment]
Using `*` would not work in the long run as `mdshare` will (and already does) provide more data than actually used in the tutorial. We will either need a script or a special file name pattern for all tutorial-related data.

**Comment by marscher** [comment]
binder does not like ftp at all. Is the same data available over http?

**Comment by cwehmeyer** [comment]
I would not mind adding a special function to `mdshare` to load a collection similar to the (now deprecated) `mdshare.load()` function which uses `urllib.request. urlretrieve` instead of FTP.

The FTP stuff is actually only there to obtain a list of available files and enable wildcard use. If you know a better way to handle this, e.g. via `urllib`, please tell me.

**Comment by marscher** [comment]
On 28.05.2018 16:37, Christoph Wehmeyer wrote:
> I would not mind adding a special function to `mdshare` to load a collection similar to the (now deprecated) `mdshare.load()` function which uses `urllib.request. urlretrieve` instead of FTP.
> 
> The FTP stuff is actually only there to obtain a list of available files and enable wildcard use. If you know a better way to handle this, e.g. via `urllib`, please tell me.
> 

I have added a script to download the collections like this (probably at
a certain point I will have rewritten mdshare - or just use curl with a
pattern and a few options).
https://github.com/marscher/pyemma_tutorials/blob/binder_fetch_data/fetch_data.py

The ftp solution for the listing is quite simple, but FTP makes a lot of
assumptions on the Network (eg. active mode almost never works in
firewalled environments).

**Comment by cwehmeyer** [comment]
That file already fetches more than we need.

We know the exact filename patterns as well as the numbers of files. Using `mdshare.download_wrapper()` we can then just work through some for loops and get everything without using FTP at all.

**Comment by cwehmeyer** [comment]
By the way, `mdshare.fetch()` **always** uses FTP first to see which files (wildcard) are available before checking which files have already been downloaded.

**Comment by marscher** [comment]
even if the data is already there, mdshare is going to overwrite it. So prefetching does not cure the timeout errors caused by using active FTP.

**Comment by cwehmeyer** [comment]
> even if the data is already there, mdshare is going to overwrite it.

No, it does not. `mdshare.fetch()` first uses an ftp call to expand wildcard-based file patterns. Then it uses a non-ftp call to get the actual file **if** it is not already present.

Thus, we need an alternative for the wildcard expansion.

**Comment by marscher** [comment]
With the new http index method the offline caching works as expected at binder. Do you think we should postpone the building of a more sophisticated index @cwehmeyer? There are more urgent things to do in my opinion.

**Comment by cwehmeyer** [comment]
I agree, the index can wait.
