### ISSUE TITLE
Estimation/validation figure

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#142]
- [x] Check whether zooming improves difference visibility in (b).
- [x] Missing description for line styles and grey area in (e).
- [x] Text description of (f) should focus on content not interpretation.
- [x] Overlap in (f) prevents black lines from being seen (this would require rewriting pyemma's plot_cktest function).
- [x] Extract (e,f) as individual figure to mitigate current column height overflow.

**Comment by thempel** [comment]
Well, I'd say that they are sort of visible if you zoom in, but I agree that's not optimal. I also can't think of a great solution here... maybe adjusting the line style of the blue line to ':' or just 'o' would be a quick and dirty fix, if that works with the API? Still not optimal though.

**Comment by cwehmeyer** [comment]
> Well, I'd say that they are sort of visible if you zoom in, but I agree that's not optimal. I also can't think of a great solution here... maybe adjusting the line style of the blue line to ':' or just 'o' would be a quick and dirty fix, if that works with the API? Still not optimal though.

I see a minimal improve with scaling down the line widths but the API does not allow for much more control.

I would stick with line width scaling for now and address this problem later with a proper refactoring of `pyemma.plots.markovtests.py` (markovmodel/pyemma#1353).
