### ISSUE TITLE
Hyperparameter choice: VAMP-2 lagtime

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#144]
Section 3.2 requires an explanation why we use lagtime 0.5 ns for the VAMP-2 analysis (point to NB 00).

**Comment by marscher** [comment]
I guess the same applies for the used TICA lag time?

**Comment by cwehmeyer** [comment]
Yes, you're right.

**Comment by franknoe** [comment]
If we use VAMP/TICA to select features or find a relevant subspace to work in, the main idea is that this choice should be invariant wrt the lagtime within a significant lagtime range.

**Comment by cwehmeyer** [comment]
> If we use VAMP/TICA to select features or find a relevant subspace to work in, the main idea is that this choice should be invariant wrt the lagtime within a significant lagtime range.

That's what we look at in the notebook. The manuscript, however, lacks this information.

We need to decide whether to refer more clearly to the showcase notebook or include more figures and explanation in the manuscript.

Personally, I do not like the latter as it would clutter the workflow description and distract from the bigger picture.
