### ISSUE TITLE
Better connection between manuscript and the specific tutorial notebooks

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#170]
> Make more explicit connections between the other tutorials (i.e. 01-07), and sections of the text. When there is a section of the text that describes a concept described in the tutorial, it should explicitly list which tutorial it is, and use what is in the tutorial to make the connection between the paper and the note book explicit.
>
> For example, section 3.7 talks about connecting MSM's to experimental observables, which seems like it should explicitly reference notebook 06 as well as the section of 00 that is appropriate. However 1) the notebook dealing with this topic is not referenced anywhere and 2) the experimental observables in notebook 06 are j-couplings for molecules, as well as a toy problems. That these examples exist in the tutorial should be described at some level in the text. Similar comments apply to the other sections and the other 01-08 notebooks associated with these sections. Note that since the tutorials are relatively self-contained, there does not need to be a full description in the paper; but enough information should be in the paper to indicate what questions/problems are specifically covered in the tutorials, and why those examples were selected.

**Comment by thempel** [comment]
Will do some interlinking between tutorials 01-07.

**Comment by marscher** [comment]
The experimental nb still needs linkage

**Comment by psolsson** [comment]
i will look into the experimental linkage
