### ISSUE TITLE
Specific changes to the manuscript

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#171]
There are several small points to address:

- [x] Page 1: "distances. (see [10]" -> remove period.
- [x] "By assessing how well the approximated transition probability matrix adheres to the CK property," Should include a link to citation discussing the criteria?
- [x] In Theory section, provide specific references to not only the original scientific papers citing them the different methods and concepts, but mention specific chapters / articles that are the best to learn about them. The HMM section is particuarly terse wirth a lot of definitions, and could use specific recommended citations with more details (not just the original ones). You don't need to explain all of the details (this is a tutorial) but should show people where to get the details. There are other places where this occurs, for example, the description of multiensemble Markov Models. Again, since it's not a review, you don't have to explain everything, but explicitly state recommendations for where to look for more information if you bring up new concepts that are not covered in the tutorial.
- [x] Figure 4: Make it easier to interpret alone. We would suggest saying what the conclusions the data demonstrate, in addition to describing the data. Figures 3, 5 and 6 are good examples of more self-contained figures with conclusions included.
- [x] Page 9: "make use of the specific Jupyter notebooks distributed with PyEMMA." For the methods you discuss, specify which notebooks address those features and where to find them.
- [x] "Additional technical challenges for large systems include high demands on memory and computation time; we explain how to deal with those in the tutorials." Say where in the tutorials this is done.

**Comment by franknoe** [comment]
Acknowledgements need to be completed (please check in the future that funding for *all* authors is there. SFBs must specify the project number).

TH acknowledges financial support from Deutsche Forschungsgemeinschaft (SFB/TRR 186, Project A12). FN and BEH acknowledge funding from European Commission (ERC CoG 772230 "ScaleCell"). FN acknowledges funding from Deutsche Forschungsgemeinschaft (SFB 1114, Projects A04 and C03, NO 825/2-2). SO acknowledges a postdoctoral fellowship from the Alexander von Humboldt Foundation.

**Comment by brookehus** [comment]
I will look at item 3 (citation stuff) either this afternoon or first thing tomorrow morning

**Comment by thempel** [comment]
@brookehus I did some restructuring of the HMM section in branch `details`. Maybe you want togo on with this branch or merge into your branch.

**Comment by brookehus** [comment]
I will PR to your branch!

**Comment by thempel** [comment]
Item 5 done by @cwehmeyer by 040c423

**Comment by franknoe** [comment]
Please add as a second affiliation for me:

Rice University, Department of Chemistry, Houston, Texas 77005, United States

**Comment by thempel** [comment]
@franknoe could you provide a street address?

**Comment by brookehus** [comment]
Online it says 6100 Main St., Houston, TX 77005 for the chem dept

**Comment by franknoe** [comment]
thanks, right
