### ISSUE TITLE
TODOs before ASAP version

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#186]
- [x] Notebook 07 is referenced a lot in Sec. 2.3 but we haven't even introduced the notebooks yet. Maybe something referring to the discussion of the notebooks in a future section is needed.
- [x] Change funding statement so it either explicitly covers all authors or somehow generally describes everyone - ask @franknoe?
- [x] Cross-check paper edit document with pdf rendering to make sure I caught everything. Some things I deliberately didn't address were:
- [x] Comments in item 2 of Sec. 2.1
- [x] Comments after Eqn. 11
- [x] Comments in paragraph 2 of Sec. 2.3
- [x] Wording suggestions in Sec. 3.7, paragraph 3
- [x] Comments on Sec. 3.8
- [x] Anything to do with SI units

**Comment by brookehus** [comment]
@cwehmeyer @thempel do either of you want to take this on since it's the stuff I deliberately didn't do? And then I'll look it over?

**Comment by brookehus** [comment]
Or we can look at any of the wording stuff together of course. I just didn't want to make a change without discussing w/ either of you. Or @marscher
