### ISSUE TITLE
chapman-kolmogorov test Error

### ISSUE THREAD

**Issue by sundelinllnl** [markovmodel/pyemma_tutorials#196]
Hi, pyemma developers,

I am following the pyemma tutorials for the pentapeptide and I encountered errors at the CK test step, with the following error message:
"m = self._D.shape[0]  # this will raise and exception if self._D doesn't exist yet.
AttributeError: 'BayesianMSM' object has no attribute '_D'"

So, how to solve this problem.

Thanks
Delin

**Comment by marscher** [comment]
cross-posted markovmodel/pyemma#1416, fixed by markovmodel/pyemma#1418

**Comment by omkantnirala** [comment]
Hello pyEMMA Team, 
I am getting this Error after running below code.
"nstates = 5
cktest = msm.cktest(nstates, mlags=6)
pyemma.plots.plot_cktest(cktest, dt=0.1, units='ns');"
Please tell me how can i fix it?
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[34], line 2
      1 nstates = 5
----> 2 cktest = msm.cktest(nstates, mlags=6)
      3 pyemma.plots.plot_cktest(cktest, dt=0.1, units='ns');

AttributeError: module 'pyemma.msm' has no attribute 'cktest'
