### ISSUE TITLE
mlags meaning

### ISSUE THREAD

**Issue by andresilvapimentel** [markovmodel/pyemma_tutorials#197]
I am learning about the pyemma package.
What does mlags mean in the Chapman-Kolmogorov Test? Why do multiples of lag times make difference for testing the Model?
Could you explain about it, please? Could you explain the procedure to peform the analysis of multiples of lag times, please?
How do multiples of lag times split the fast and slow processes?

**Comment by clonker** [comment]
Please let me refer you to the [PyEMMA2 publication](https://pubs.acs.org/doi/10.1021/acs.jctc.5b00743) where the Chapman-Kolmogorov test is detailed better than I could do it within a GitHub issue.
