### ISSUE TITLE
Issue on clustering after changing the pip installation and trying conda installation

### ISSUE THREAD

**Issue by andresilvapimentel** [markovmodel/pyemma_tutorials#199]
I have used pyemma with no issue for over a year installing it on google colab with:
pip install wheel
pip install pyemma

Suddenly, it stopped working last week. I do not know why. I found the following issue:

Building wheels for collected packages: pyemma
  Building wheel for pyemma (PEP 517) ... error
  ERROR: Failed building wheel for pyemma
Failed to build pyemma
ERROR: Could not build wheels for pyemma which use PEP 517 and cannot be installed directly

Then, I tried to install it by using the conda package on google colab bu using the following:

! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
! chmod +x Miniconda3-py37_4.8.2-Linux-x86_64.sh
! bash ./Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -f -p /usr/local
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

!curl -s https://raw.githubusercontent.com/markovmodel/PyEMMA/devel/install_miniconda%2Bpyemma.sh | bash
!conda install -c conda-forge pyemma

It works pretty well until clustering. I found the following using:
cluster = pyemma.coordinates.cluster_kmeans(tica_output, k=k, max_iter=50, stride=50)

/usr/local/lib/python3.7/site-packages/deeptime/data/_pbf_simulator.py in <module>()
      3 from threadpoolctl import threadpool_limits
      4 
----> 5 from . import _data_bindings as bd
      6 from ..util.decorators import plotting_function
      7 from ..util.parallel import handle_n_jobs, joining

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python3.7/site-packages/deeptime/data/_data_bindings.cpython-37m-x86_64-linux-gnu.so)

Please, let me know what is going on. hanks.

**Comment by clonker** [comment]
We probably have to do a patch-release of pyemma. In the meantime you can try this:
`!pip install git+https://github.com/markovmodel/pyemma.git@devel`

**Comment by clonker** [comment]
patch is out, would you mind trying if everything works for you now? the pyemma version you are looking for is `2.5.10`.
