### ISSUE TITLE
Error in Visualize_metstable() step

### ISSUE THREAD

**Issue by gokulalgates** [markovmodel/pyemma_tutorials#22]
I am getting the following error when i run this step 
my_samples = [pyemma.coordinates.save_traj(files, idist, outfile=None, top=pdb)
              for idist in msm.sample_by_distributions(coarse_msm.metastable_distributions, 50)]

visualize_metastable(my_samples, cmap)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-a71e1fb56cdf> in <module>()
      4 
      5 my_samples = [pyemma.coordinates.save_traj(files, idist, outfile=None, top=p)
----> 6               for idist in msm.sample_by_distributions(coarse_msm.metastable_distributions, 50)]
      7 
      8 visualize_metastable(my_samples, cmap, selection='backbone')

<ipython-input-31-a71e1fb56cdf> in <listcomp>(.0)
      4 
      5 my_samples = [pyemma.coordinates.save_traj(files, idist, outfile=None, top=p)
----> 6               for idist in msm.sample_by_distributions(coarse_msm.metastable_distributions, 50)]
      7 
      8 visualize_metastable(my_samples, cmap, selection='backbone')

~/miniconda3/lib/python3.5/site-packages/pyemma/coordinates/api.py in save_traj(traj_inp, indexes, outfile, top, stride, chunksize, image_molecules, verbose)
    741                          % (len(trajfiles), indexes[:,0].max()))
    742 
--> 743     traj = frames_from_files(trajfiles, top, indexes, chunksize, stride, reader=reader)
    744 
    745     # Avoid broken molecules

~/miniconda3/lib/python3.5/site-packages/pyemma/coordinates/data/util/frames_from_file.py in frames_from_files(files, top, frames, chunksize, stride, verbose, copy_not_join, reader)
    113                                 largest=largest_ind_in_traj,
    114                                 filename=reader.filenames[itraj],
--> 115                                 length=length))
    116 
    117     def set_reader_return_traj_objects(reader, flag):

ValueError: largest specified index (773234.0 * stride=773234.0 * 1=773234) is larger than trajectory length '/data4/SINGAM/CNT_PROTEIn/CNT_PROTEIN_IONS/CNT_PROTEIn/output/run_23_cnt.dcd' = 13001
'

Can you please help me in fixing the code. Even with the tutorial (pentapetide) I am getting similar error

**Comment by cwehmeyer** [comment]
In the pentapeptide part of this tutorial is a mistake: we are reading a fragmented trajectory (single trajectory split into multiple files) which are concatenated by pyemma's load function
```python
data = pyemma.coordinates.load([files], features=feat)
```
if you place the list of files in another encapsulating list (as shown above). Later, when we sample frames from the trajectory to visualise metastable states, I forgot the encapsulating list:
```python
my_samples = [pyemma.coordinates.save_traj(files, idist, outfile=None, top=pdb)
              for idist in msm.sample_by_distributions(coarse_msm.metastable_distributions, 50)]
```
To fix this issue, just use `[files]` instead of `files`as shown here:
```python
my_samples = [pyemma.coordinates.save_traj([files], idist, outfile=None, top=pdb)
              for idist in msm.sample_by_distributions(coarse_msm.metastable_distributions, 50)]
```

Thanks for pointing this out!

Looking at the traceback, I suspect that your own application suffers the same problem. But without knowing what kind of data you are working with, I cannot say for sure.

**Comment by marscher** [comment]
Thanks for testing @gokulalgates and good catch!

@cwehmeyer maybe we should pass the constructed reader in this spot? Also show the users once, that the actual reader is a FragmentedTrajectoryReader.
