### ISSUE TITLE
provide unit tests for notebooks

### ISSUE THREAD

**Issue by marscher** [markovmodel/pyemma_tutorials#31]
We can use hidden cells to check for the outcome of the actual cells. There is a notebook extension to quickly edit the metadata of a cell to hide it. During the test execution these cells will still be picked up and executed, but are not visible to the user.

This way we can ensure that the notebooks are doing their job even with an updated version of pyemma (or its dependencies).

**Comment by marscher** [comment]
https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/hide_input/readme.html

**Comment by cwehmeyer** [comment]
@marscher: can we test if cells raise an exception instead of just skipping them?

**Comment by marscher** [comment]
On 06/21/2018 02:46 PM, Christoph Wehmeyer wrote:
> @marscher <https://github.com/marscher>: can we test if cells raise an
> exception instead of just skipping them?

I think this would only be possible if we rewrite the cells code with a
try except block. Without it it would involve writing our own notebook
executor which is absolutely overkill.

**Comment by cwehmeyer** [comment]
I am not in favour of `try-except` blocks in the exercises. It might make sense., though, in special cases where we expect a special exception, e.,g., #41.

**Comment by marscher** [comment]
We agreed that exception safety tests are sufficient. We shall use periodic builds to ensure this property. Testing each individual result is too verbose.
