### ISSUE TITLE
Wrap up missing in notebook 6

### ISSUE THREAD

**Issue by psolsson** [markovmodel/pyemma_tutorials#33]
I will have a look at it tomorrow.

**Comment by cwehmeyer** [comment]
Notebook 5 (HMMs) has a wrap up...
<details>

In this notebook, we have learned how to use a hidden Markov state model (HMM) and how they differ from an MSM. In detail, we have used
- `pyemma.msm.timescales_hmsm()` function to obtain an implied timescale object for HMMs,
- `pyemma.msm.estimate_hidden_markov_model()` to estimate a regular HMM,
- `pyemma.msm.bayesian_hidden_markov_model()` to estimate a Bayesian HMM, and
- the `metastable_assignments` attribute of an HMM object to access the metastable membership of discrete states.
</details>

... but notebook 6 has not. Thanks for taking care!

**Comment by cwehmeyer** [comment]
Solved via #35.
