### ISSUE TITLE
help in selection number of cluster center and lag time

### ISSUE THREAD

**Issue by gokulalgates** [markovmodel/pyemma_tutorials#36]
Hi 

I am attaching a pdf file of my results can you please help me in selecting a proper lag time and clustercenter for my system. I think I am doing something wrong here can you please help me understand the lag time and clustercenters? 

with regards
Singam
[MSM_GRAPH_DISTANCE_CA.pdf](https://github.com/markovmodel/pyemma_tutorials/files/2112322/MSM_GRAPH_DISTANCE_CA.pdf)

**Comment by cwehmeyer** [comment]
> [...] please help me in selecting a proper lag time and clustercenter for my system.

Without more knowledge about your system, I would say that this seems like a good case for VAMP-based feature selection (notebook 8).

> [...] can you please help me understand the lag time and clustercenters?

How familiar are you with the theory behind the Markov state model approach?

**Comment by gokulalgates** [comment]
Thank you for your suggestion about VAMP-based feature selection. I did analysed using VAMP-based feature selection I selected distance_ca() method which has the better  VAMP score when compare to other features. I am new to MSM analysis, but I understood some of the basic concept of MSM.

**Comment by gokulalgates** [comment]
I am working on the Trp-Cage protein models with 60 different trajectories of length 300 ns. hope this helps?

**Comment by cwehmeyer** [comment]
What is the trajectory time step?

**Comment by gokulalgates** [comment]
trajectory is saved for every 20 ps.

**Comment by cwehmeyer** [comment]
OK, let's try something...

```python
tica = pyemma.coordinates.tica(data, lag=200, dim=5)
cluster = pyemma.coordinates.cluster_kmeans(tica, k=500, stride=10)
its = pyemma.msm.its(cluster.dtrajs, lags=10000)
pyemma.plots.plot_implied_timescales(its)
```

How are the implied timescales looking?

**Comment by gokulalgates** [comment]
Sending herewith Free energy at different lag time and ITS for the given code. i got this warning 
Following warning 
![its](https://user-images.githubusercontent.com/9268265/41560853-fa51d50a-730d-11e8-8160-9a2644488ceb.png)

18-06-18 15:39:12 pyemma.msm.estimators.maximum_likelihood_msm.MaximumLikelihoodMSM[7] WARNING  Ignored error during estimation: Stationary distribution contains entries smaller than 1e-15 during iteration

![freeenergy](https://user-images.githubusercontent.com/9268265/41560671-7961b208-730d-11e8-84f7-02fb1c6aec08.png)

**Comment by gokulalgates** [comment]
I attached wrong Free Energy in my previous comment
![freeenergy](https://user-images.githubusercontent.com/9268265/41561056-79163444-730e-11e8-835c-2ee1ecd7701e.png)

**Comment by cwehmeyer** [comment]
For comparison, here are implied timescales for a single long trp-cage trajectory using Ca distances and the above TICA/cluster settings:
![image](https://user-images.githubusercontent.com/5278589/41561448-46b886fa-734a-11e8-83e1-46e5197cbde6.png)
In this case, I need an MSM lag time of 100 ns or more in order to converge the implied timescales.

Looking at you data, trajectories of 300 ns length might be a bit short. How have you initialised your simulations, are all 60 trajectories starting from the same configuration?

**Comment by gokulalgates** [comment]
All my Simulations were started with different configuration of TrpCage on nano-material.

**Comment by gokulalgates** [comment]
Can you please send me the example notebook of TrpCage MSM model for reference to check if i am doing it right.?

**Comment by cwehmeyer** [comment]
Using a single trajectory with time step 0.2 ns, I used the following code:
```python
features = pyemma.coordinates.featurizer(pdb_file)
features.add_distances_ca()
data = pyemma.coordinates.load(traj_files, features=features)
tica = pyemma.coordinates.tica(data, lag=20, dim=5)
cluster = pyemma.coordinates.cluster_kmeans(tica, k=500, max_iter=50, stride=10)
its = pyemma.msm.its(cluster.dtrajs, lags=5000, nits=4)
ax = pyemma.plots.plot_implied_timescales(
    its, dt=[0.0002, 0.0002], units=['$\mu s$', '$\mu s$'])
ax.set_xlim(0, 1.0)
ax.set_ylim(0.1, 4)
```

Based on the peak around 1600 steps in your ITS plot and the warning that (numerically) states are lost, I guess that you have a connectivity problem in your data, i.e., some states are only weakly connected and give rise to unphysically high implied timescales. One way to solve such a problem would be to increase the sampling by running additional (and longer) simulations.
