### ISSUE TITLE
Models: maximum likelihood vs Bayesian

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#38]
We need some additional text on the difference between maximum likelihood models and Bayesian models; e.g., how to get error bars from the latter.

**Comment by thempel** [comment]
Where would you include that? Notebook 03 - MSM estimation and validation?

**Comment by cwehmeyer** [comment]
The conceptual difference should definitely go into 03, but I would like to show how it is used to get error bars in 04 and 06.

**Comment by psolsson** [comment]
I think it makes sense to mention both in 03 and highlight how you get errors on time-scales and ck-tests. In 04 we can show `sample_mean`, `sample_conf` and `sample_std` for example in the context of the MFPTs to show how the Bayesian model allows us quantify errors in these quantities -- I use these functions in 06, but I think it would make sense to also mention them in an earlier notebook. Thoughts?

**Comment by cwehmeyer** [comment]
Good point to focus on CK+ITS error bars in NB04. We only need to adapt the text then.

**Comment by thempel** [comment]
Yes, I'll  try to explain it at examples that already use Bayesian MSMs and show how to explicitly get the estimates outside of `timescales_msm(dtrajs, erros='Bayes')` using the functions Simon mentioned. I'd rather avoid explaining Bayesian HMMs though.
