### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#40]
The README file needs some updates, e.g.,

- [x] the recommended installation of Python, PyEMMA, and Jupyter;
- [x] installation of the tutorial requirements;
- [ ] troubleshooting (#12);
- [x] license information (#48);
- [x] how to use the tutorial.

Feel free to extend this list.

**Comment by marscher** [comment]
I will take care of the first two point. There will be a conda-forge pkg for the tutorials I guess. We can use a release candidate versioning scheme prior publishing.

**Comment by cwehmeyer** [comment]
That's a good idea!

**Comment by marscher** [comment]
I think the information on how to use the tutorial is also (briefly) covered in the readme.
