### ISSUE TITLE
Notebook speedup and stability

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#46]
While I cannot reproduce it on my machines, I frequently see problems like the following in the CI tests:

```
pyemma_tutorials/notebooks/06-expectations-and-observables.ipynb::Cell 21 <- [..]
06-expectations-and-observables.ipynb Too long with no output (exceeded 10m0s)
```
(from  #43)

We need to make sure that our tutorials are stable and fast on all reasonable platforms.

**Comment by cwehmeyer** [comment]
@marscher: that worked pretty well! Would you recommend to use `n_jobs=None` or some fixed amount of threads in the notebooks?

**Comment by marscher** [comment]
On 28.06.2018 17:36, Christoph Wehmeyer wrote:
> @marscher: that worked pretty well! Would you recommend to use `n_jobs=None` or some fixed amount of threads in the notebooks?
> 

None, will use as much resources as possible - so this should also gain
as much speed up as possible (assumed there are no other heavy processes
running).
For the sampling I really dunno what is the best setting, we should test it.

**Comment by cwehmeyer** [comment]
I'm going with `n_jobs=None` for now. Thanks again for the suggestion!
