### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#48]
We should maybe include a license for this repository. Given that we are providing instructions and not (primarily) software, I'd vote for a creative commons type license.

@franknoe and @marscher, what do you think?

**Comment by franknoe** [comment]
As open as possible. How about BSD3, or does this not  make sense for this type of software?On Jun 27, 2018 9:45 AM, Christoph Wehmeyer <notifications@github.com> wrote:We should maybe include a license for this repository. Given that we are providing instructions and not (primarily) software, I'd vote for a creative commons type license.
@franknoe and @marscher, what do you think?

**Comment by cwehmeyer** [comment]
BSD/(L)GPL are not a very good choice for documents and this tutorial is (at least in my opinion) more a document than a software package. In addition: the manuscript itself will be part of this repository and that should (as recommended by www.livecomsjournal.org) be licensed under CC BY 4.0:

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

This license is as open as possible (free academic + commercial use, non-viral) and only requires attribution.

**Comment by marscher** [comment]
I think CC 4.0 is a good choice

**Comment by marscher** [comment]
@thempel, @psolsson Are you also ok with this license? For conda-forge we also need to specify the license, so it would be nice to resolve this one soon.

**Comment by thempel** [comment]
I'm clearly not an expert on this, but it sounds reasonable on the first sight...

**Comment by psolsson** [comment]
I ecco Tim.

**Comment by cwehmeyer** [comment]
OK then. I'll add the badge and license information to the README and notebooks.

@marscher: do we need a license **file** for conda-forge?

**Comment by marscher** [comment]
On 28.06.2018 15:31, Christoph Wehmeyer wrote:
> OK then. I'll add the badge and license information to the README and notebooks.
> 
> @marscher: do we need a license **file** for conda-forge?
> 

Thanks again. We need this file for CF.

**Comment by cwehmeyer** [comment]
> We need this file for CF.

OK, I'll add that too. Thanks!
