### ISSUE TITLE
Add n_jobs=None to all Bayesian models' cktest() calls

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#56]
#46 leaves some room for improvement as PyEMMA does not (yet) support `n_jobs=None` for `cktest()` calls which is likely a huge time saver for Bayesian HMMs.

**Comment by marscher** [comment]
I think we should change njobs=None for all cktests in pyemma, since I consider this feature stable now.

**Comment by marscher** [comment]
fixed by markovmodel/pyemma#1330
