### ISSUE TITLE
conda environments

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#58]
README.md assumes the user uses conda environments. Most users are not familiar with conda environments and very few people use them. I think it's OK to give that as one option, but there should be a way to do it without environments that should work at least in non-pathological cases.

Does 'conda activate pyemma_tutorials' set the conda environment until changing it back or is that setting only valid in the current shell? We certainly don't want to put the user in a situation where their default environments is disabled after using these notebooks

**Comment by cwehmeyer** [comment]
> README.md assumes the user uses conda environments. Most users are not familiar with conda environments and very few people use them. I think it's OK to give that as one option, but there should be a way to do it without environments that should work at least in non-pathological cases.

I agree. We should keep the conda environment as the recommended option, because it bundles a few necessary steps into one, but also describe how to install all necessary dependencies and activate the notebook plugins.

> Does 'conda activate pyemma_tutorials' set the conda environment until changing it back or is that setting only valid in the current shell? We certainly don't want to put the user in a situation where their default environments is disabled after using these notebooks

The environment is active only in the current shell and does not remove the default.

**Comment by marscher** [comment]
If I invoke conda activate locally, it states that the command needs a special setup involving fiddeling around with bashrc. This needs to be avoided, because the average user will only mess things up.

**Comment by marscher** [comment]
This seems to affect only old miniconda installations, which were set active by modifying the PATH and now the recommended thing is to source a script within bashrc.

I'm closing this one, because conda activate does not alter the default env, but is just session wide.
