### ISSUE TITLE
Problems with notebook 02

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#6]
Via #4 
- [x] Do people know what a slow process is when it is mentioned for the first time? It's not really captured by histograms.
- [x] Not quite sure what the histogram of discrete trajectories teaches people... given that in most cases, one cannot reproduce those histograms, people might ask later why they don't see this with their own data in pyemma.

**Comment by cwehmeyer** [comment]
After reviewing the code regarding the histogram of discrete trajectories, I'd vote to just remove this plot without further comment. Would you agree, @thempel and @marscher?

**Comment by marscher** [comment]
On 28.05.2018 15:07, Christoph Wehmeyer wrote:
> After reviewing the code regarding the histogram of discrete trajectories, I'd vote to just remove this plot without further comment. Would you agree, @thempel and @marscher?
> 
 I do.
