### ISSUE TITLE
README install instructions

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#60]
After installing things manually with conda (pyemma, nglview, mdshare), things seem to work. I suggest to make that the standard method of using which means it should be described in the README first.

**Comment by cwehmeyer** [comment]
I think it should be possible to put all installation and plugin activation steps into a single code listing. Do you agree @marscher?

**Comment by marscher** [comment]
This has already happened, we just need to publish the conda package.

**Comment by franknoe** [comment]
I don't understand how this has happened, the github in the README does not contain a section for a "normal" conda install (without environments).

**Comment by marscher** [comment]
We have the package on conda-forge right now. The instructions are in line - so I consider this one finally fixed.
