### ISSUE TITLE
Notebook 4/5

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#66]
I suggest a significant change in notebook 4 (may affect notebook 5 too). 

First I would like to avoid the usage of the MSM method 'coarse_grain' because that currently just calls a HMM estimation. We haven't implemented any real MSM-based coarse-graining, it is really a new estimation, and should better be accompanied by ITS, CK-test etc. So I suggest to postpone the computation of a coarse-grained transition matrix to notebook 5 and make notebook 5 part of the standard set of notebooks.

Notebook 4 can and should include PCCA (computation of metastable sets). We just can't use it to compute a coarse-grained transition matrix yet. But we can compute mfpts, equilibrium probabilities, representative structures etc.

Then I am missing TPT. TPT can be done on the metastable sets without having a coarse-grained transition matrix, because the flux can be coarse-grained. So I suggest that goes into notebook 4.

Generally NB4 is quite complex and has very extensive code cells. Think of breaking them into pieces, maybe break the whole notebook into two notebooks if needed.

Finally the visualization of the four Alanine dipeptide structures is not very useful. Maybe someone with an eye for molecular structures can revise that.

**Comment by marscher** [comment]
> Finally the visualization of the four Alanine dipeptide structures is not very useful. Maybe someone with an eye for molecular structures can revise that.

@franknoe could you please elaborate what do you mean by usefulness? @gph82 and I have created this representation. We only visualize the backbone, as the discretization only uses the backbone interactions and for the sake of simplicity. When we show all the atoms it is quite a mess.
