### ISSUE TITLE
physical units

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#70]
Use physical units instead of things like "steps" whenever they are available. Please check all notebooks for that.

![image](https://user-images.githubusercontent.com/6495810/42116320-fe5371da-7bf6-11e8-9336-de3ce1b53892.png)

**Comment by thempel** [comment]
OK, let's organize this a bit with a checklist:

- [ ] 01-data-io-and-featurisation
- [ ] 02-dimension-reduction-and-discretisation
- [ ] 03-msm-estimation-and-validation
- [ ] 04-msm-coarse-graining-and-analysis
- [ ] 05-hidden-markov-state-models
- [ ] 06-expectations-and-observables
- [ ] 07-vamp-based-feature-selection
- [ ] 08-common-problems

**Comment by marscher** [comment]
What is the discrete time step in di-ala and pentapeptide though?

**Comment by cwehmeyer** [comment]
It's 1ps for di-ala and 100ps for the  pentapeptide.
