### ISSUE TITLE
Notebook 6 'isin' bug

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#71]
Note sure why this happens in cell 4 (Python 3.5, Numpy 1.11.3):

![image](https://user-images.githubusercontent.com/6495810/42116510-c6cf59d0-7bf7-11e8-8fef-c7cd76bee779.png)

**Comment by cwehmeyer** [comment]
The function `np.isin` was introduced in numpy-1.13.0. We'll either replace it or make numpy>=1.13 a dependency.

**Comment by marscher** [comment]
I think depending on a recent NumPy is a good idea. I will add this to the recipe.
