### ISSUE TITLE
AMMs?

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#72]
Somehow I was under the impression that Notebook 6 would introduce AMMs. It would be a good point to do that. Is that not desired?

**Comment by cwehmeyer** [comment]
After our last discussion we decided to limit the scope of the tutorial and AMMs did not make the cut.

@psolsson: do you think we can squeeze AMMs into 06?

**Comment by psolsson** [comment]
As @cwehmeyer says I was arguing for including them, but I understood this was outside the scope, and there would be other opportunities to present that. There is one tutorial on this in the PyEMMA documentation which is fairly new. Maybe we can just make reference to this?

**Comment by psolsson** [comment]
I have made a reference to AMMs in the 06 NB and link to the walk-through tutorial which is in the pyemma docs. I think this is a good solution as that notebook is relatively new.
