### ISSUE TITLE
notebook 6 runtime

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#73]
NB6 takes too long to run to get to the interesting part (dynamical correlations). Maybe we don't need Bayesian HMMs for that?

Also there is a weird behavior of this cell which outputs a lot of very short-lived progress bars. Unless you know better, you might assume the notebook has crashed:

![image](https://user-images.githubusercontent.com/6495810/42116828-755f166a-7bf9-11e8-8965-b8cd7e29fda8.png)

**Comment by psolsson** [comment]
I agree. I will include correlation function example for 2-Ala. I will also write a warning for users around that cell that it may take time to complete. I want to keep that example as it is the only example which is close to actual practical use.
