### ISSUE TITLE
concatenating data

### ISSUE THREAD

**Issue by thempel** [markovmodel/pyemma_tutorials#85]
I'm a bit worried about the following workflow that appears in many of our notebooks:
```python
data = pyemma.coordinates.load(...)  
data_all = np.concatenate(data)  # or tica_all
cluster = pyemma.coordinates.cluster_somehow(data_all)
```
The reason is that people love copy-pasting. Using this workflow, it's really likely to end up with estimating an MSM on concatenated discrete trajectories by calling `cluster.dtrajs`. Since all the clustering routines care about this, I strongly suggest that we remove this from all of the notebooks. We might even want to refactor the `_all` suffix to `_concatenated` or equivalent.

**Comment by cwehmeyer** [comment]
The last line of code should not appear in any notebook! Do you have an example where that happens?

> We might even want to refactor the _all suffix to _concatenated or equivalent.

That's a good idea.

**Comment by thempel** [comment]
Let's search and replace after we've merged the open PRs.

**Comment by cwehmeyer** [comment]
Besides `data` we also have `tica`, `pca`, and `dtrajs`.

**Comment by marscher** [comment]
I have also taken a look at these variables, despite this issues description.

**Comment by cwehmeyer** [comment]
I still found and replaced quite some instances in the current master.
