### ISSUE TITLE
NB00

### ISSUE THREAD

**Issue by psolsson** [markovmodel/pyemma_tutorials#94]
As I was going through this notebook I was noting a few things:
- a Bayesian MSM is estimated but its advantages are not used or shown in the analysis, specifically computation of confidence intervals. I have added this in the first plots in the spectral analysis,  In the (second): the timescale separation plot some error-propagation needs to be done in order for this to be correct.
- The visualization of the free-energy landscape just below the time-scale analysis, needs some more text. Why are two different plots shown? What is the difference? 
- several lose ends scattered TODOs.

**Comment by cwehmeyer** [comment]
> a Bayesian MSM is estimated but its advantages are not used or shown in the analysis, specifically computation of confidence intervals. I have added this in the first plots in the spectral analysis, In the (second): the timescale separation plot some error-propagation needs to be done in order for this to be correct.

Have you already pushed these changes?

> The visualization of the free-energy landscape just below the time-scale analysis, needs some more text. Why are two different plots shown? What is the difference?

On the left we show the stationary distribution. On the right we have the (reweighted) free energy surface.

**Comment by psolsson** [comment]
I addressed what I could last night and pushed it. Several loose ends remain.
