### ISSUE TITLE
Comments on the 00-showcase notebook

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#97]
Courtesy of @brookehus:

- [x] Missing labels in cell 8 (first two tics)
- [x] Elaborate more on the ITS plot in cell 12 (log-log vs log-lin, meaning of error bars)...
- [x] ~~plot_density(..., logscale=True) in cell 16?~~
- [x] Refer to the correct PCCA++ (around cell 18+) and be more clear about fuzzy memberships vs the actual assigment.
- [x] State the exact TICA variant (kinetic map)
- [x] ~~ergodic cutoff?~~
- [x] ~~use the FRET example in 00 and move the SASA to 07 again (less complexity in the showcase)?~~
- [x] use VAMP2 for determining the number of cluster centers

and @thempel
- [x] no lagtime selection based on VAMP
- [x] implied timescale fraction: change title to "implied timescale gap"?
- [x] fix seed in k-means to make it robust, increase k?
- [x] instead of mfpt network plot, use only flux and avoid rates to not confuse with a rate matrix?
- [x] mention stochasticity involved in k-means

**Comment by thempel** [comment]
I think we should decide whether or not to include links. Either, all the follow-up notebooks should be linked at the right spots or we should remove the AMM tutorial link. Right now, this is the only link, so it looks kinda lost...

**Comment by thempel** [comment]
Could we include the links to the detailed follow-up notebooks directly in the section headers, using this notebook symbol? Or should we rather add another line that contains the link?

![grafik](https://user-images.githubusercontent.com/12544861/42632665-3aeff4ce-85de-11e8-8776-124b2344baa5.png)

**Comment by cwehmeyer** [comment]
I like your version!

But let's be verbose and explain the symbol in the manuscript/README and maybe add a reminder link at the end of each section of the showcase notebook.
